### ISSUE TITLE
USER STORY Authentication - Sign Up 

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/travel-stories#1]
As a **user** I can **register an account** so that **I can add stories, comment, like, save and create a bucket list, i.e. access everything only a signed up user can access**.

Tasks:
- [x] Create sign up form
- [x] Add link in navbar
- [x] Add hooks and handlers
- [x] Connect to API
- [x] Add error messages
- [x] Add responsivness
- [x] Add css styling
- [x] Test form functionality

Acceptance criteria:
- Form input must be validated
- The form must be connected to the API so that data can be saved.
- The form must be simple and easy to understand so that users can sign up without any problems.
